import type { Metadata } from "next";
import localFont from "next/font/local";
import "../lib/i18n";
import "./globals.css";
import CustomI18nProvider from "@/context/Customi18n.provider";
import LanguageSwitcher from "@/components/language-switcher";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomI18nProvider>
          {children}
          <div className="fixed bottom-4 right-4 z-50">
            <LanguageSwitcher />
          </div>
        </CustomI18nProvider>
      </body>
    </html>
  );
}
